name: open_mail_launcher
description: "A Flutter plugin to open email apps on Android and iOS. Query installed email apps, compose emails with pre-filled content, and provide a seamless email app selection experience."
version: 0.0.1
homepage: https://github.com/sinnoorc/open_mail_launcher
repository: https://github.com/sinnoorc/open_mail_launcher
issue_tracker: https://github.com/sinnoorc/open_mail_launcher/issues

topics:
  - email
  - mail
  - compose email
  - open email app

environment:
  sdk: ^3.8.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.sinnoor.open_mail_launcher
        pluginClass: OpenMailLauncherPlugin
      ios:
        pluginClass: OpenMailLauncherPlugin
